CREATE USER kratos WITH PASSWORD 'kratos';
CREATE USER openfga WITH PASSWORD 'openfga';
CREATE USER groups WITH PASSWORD 'groups';

CREATE DATABASE kratos;
GRANT ALL PRIVILEGES ON DATABASE kratos TO kratos;
ALTER DATABASE kratos OWNER TO kratos;

CREATE DATABASE openfga;
GRANT ALL PRIVILEGES ON DATABASE openfga TO openfga;
ALTER DATABASE openfga OWNER TO openfga;

CREATE DATABASE groups;
GRANT ALL PRIVILEGES ON DATABASE groups TO groups;
ALTER DATABASE groups OWNER TO groups;
