name: e2e test
run-name: E2E test steps for ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_call:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.26'

      - name: Install Podman
        uses: redhat-actions/podman-install@aea6ff44f2a4a82da13d22061ce73443a125925d # main

      - name: Setup podman for rootless (standard GitHub runner user)
        run: systemctl --user enable --now podman.socket

      - name: Run E2E tests
        run: make test-e2e
        env:
          DOCKER_HOST: "unix://$XDG_RUNTIME_DIR/podman/podman.sock"
